services:
  postgres:
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_book_master_db
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"
